MODEL:
  TYPE: 'fcl_1'

SOLVER:
  WEIGHT_DECAY: 0.01
  REG: 0.001

FIT:
  DATASET: 'cifar10'
  BASE_LR: 0.08
  LR_POLICY: 'time_decay'
  DECAY_RATE: 0.06
  EPOCHS: 10000

TRAIN:
  DATASET: 'cifar10'
  BASE_LR: 0.08
  LR_POLICY: 'time_decay'
  DECAY_RATE: 0.008
  EPOCHS: 100

TEST:
  DATASET: 'cifar10'

OUTPUT_DIR: '.'
